import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import "@/styles/liquid-glass.css";
import { cn } from "@/lib/utils";
import { ShaderExcludeProvider } from "@/components/ShaderExcludeContext";
import MouseShader from "@/components/MouseShader";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable, "scroll-smooth scroll-pt-30")}
    >
      
      <body className="min-h-full flex flex-col">

    <ShaderExcludeProvider>
      <MouseShader
  rippleIntensity={0.01}
  rippleSpeed={2.0}
  rippleRadius={10.0}
  accelThreshold={0.015} // Optional: Adjust how sensitive the fast flick streak is
  className="bg-slate-900 border-none"
>
        {children}
        </MouseShader>
        </ShaderExcludeProvider>
        </body>
    </html>
  );
}
